#!/usr/bin/env bash
# Install the host-side update agent for one relay.
#
# The agent is what actually carries out an update the admin console asks for:
# the relay container has no Docker socket (see src/update.rs for why it never
# gets one), so it writes a request file and this runs on the host as root.
#
# One relay per install. A host running several relays gets several instances,
# each with its own config directory, compose service and health URL -- which is
# the whole reason this is generated rather than a pair of static unit files.
#
# Usage:
#   scripts/install-update-agent.sh NAME REPO_DIR CONFIG_DIR SERVICE HEALTH_URL [COMPOSE_FILE]
#
# Example -- the two relays on this host:
#   scripts/install-update-agent.sh public /root/obelisk-relay \
#       /root/obelisk-relay/public-config public_relay http://127.0.0.1:8081/health
#   scripts/install-update-agent.sh lacrypta /root/lacrypta-relay \
#       /root/lacrypta-relay/config relay http://127.0.0.1:8083/health \
#       compose.vps.yml
#
# Re-running with the same NAME updates that instance in place.

set -euo pipefail

usage() {
  sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'
  exit 2
}

[[ $# -ge 5 ]] || usage

NAME="$1"
REPO_DIR="$2"
CONFIG_DIR="$3"
SERVICE="$4"
HEALTH_URL="$5"
COMPOSE_FILE="${6:-}"

[[ "$NAME" =~ ^[a-z0-9][a-z0-9-]{0,31}$ ]] || {
  echo "error: NAME must be lowercase alphanumeric with dashes" >&2; exit 2; }
[[ -d "$REPO_DIR" ]] || { echo "error: no such directory: $REPO_DIR" >&2; exit 2; }
[[ -d "$CONFIG_DIR" ]] || { echo "error: no such directory: $CONFIG_DIR" >&2; exit 2; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
UPDATER="$SCRIPT_DIR/relay-updater.sh"
[[ -x "$UPDATER" ]] || { echo "error: $UPDATER is not executable" >&2; exit 2; }

UNIT="obelisk-relay-update-$NAME"
ENV_DIR=/etc/obelisk-relay-update
ENV_FILE="$ENV_DIR/$NAME.env"

mkdir -p "$ENV_DIR"

# The updater reads all of its wiring from here, so a path change is an edit to
# one file rather than to three units.
cat > "$ENV_FILE" <<EOF
# Generated by scripts/install-update-agent.sh for the "$NAME" relay.
RELAY_REPO_DIR=$REPO_DIR
RELAY_CONFIG_DIR=$CONFIG_DIR
RELAY_COMPOSE_SERVICE=$SERVICE
RELAY_HEALTH_URL=$HEALTH_URL
RELAY_ENV_FILE=$REPO_DIR/.env
EOF
[[ -n "$COMPOSE_FILE" ]] && echo "RELAY_COMPOSE_FILE=$COMPOSE_FILE" >> "$ENV_FILE"
chmod 0644 "$ENV_FILE"

cat > "/etc/systemd/system/$UNIT.service" <<EOF
# Apply an update requested from the "$NAME" relay's admin console.
# Generated by scripts/install-update-agent.sh -- edit $ENV_FILE, not this file.
[Unit]
Description=Apply a relay update requested from the $NAME admin console
Documentation=file://$REPO_DIR/docs/updating.md
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
EnvironmentFile=$ENV_FILE
ExecStart=$UPDATER run
# An update pulls an image and waits on a health check; the script's own
# rollback has to fit inside this budget too.
TimeoutStartSec=900
ProtectHome=yes
ProtectSystem=full
ReadWritePaths=$REPO_DIR
NoNewPrivileges=yes

[Install]
WantedBy=multi-user.target
EOF

cat > "/etc/systemd/system/$UNIT.path" <<EOF
# Fire the moment the $NAME relay's console queues an update.
# Generated by scripts/install-update-agent.sh.
[Unit]
Description=Watch for an update request from the $NAME admin console
Documentation=file://$REPO_DIR/docs/updating.md

[Path]
PathExists=$CONFIG_DIR/update-request.json
Unit=$UNIT.service

[Install]
WantedBy=multi-user.target
EOF

cat > "/etc/systemd/system/$UNIT.timer" <<EOF
# Heartbeat, so the console can tell "installed and idle" from "never
# installed" -- without one it would offer a button whose request nothing reads.
# Generated by scripts/install-update-agent.sh.
[Unit]
Description=Heartbeat for the $NAME relay update agent
Documentation=file://$REPO_DIR/docs/updating.md

[Timer]
OnBootSec=1min
OnUnitActiveSec=10min
Unit=$UNIT.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now "$UNIT.path" "$UNIT.timer"

# Write a heartbeat immediately: the timer's first run is a minute out, and
# until one exists the console reports no agent.
env -i PATH="$PATH" bash -c "set -a; . '$ENV_FILE'; set +a; '$UPDATER' heartbeat"

echo "Installed $UNIT (.path, .timer) for $CONFIG_DIR"
echo "Heartbeat: $CONFIG_DIR/update-agent.json"
